---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["area/dependencies"]
    groups:
      go-mod:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["area/dependencies"]
    groups:
      github-actions:
        patterns: ["*"]
