---
name: "Build & Test"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "!dependabot/*"
      - "*"
  pull_request:
    branches:
      - "*"
  merge_group:
    types:
      - "checks_requested"
jobs:
  build:
    name: "Build Binary"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/actions/go-build@main"

  image-build:
    name: "Build Container Image"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/docker-build@main"

  unit:
    name: "Run Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/action-spicedb@v1"
      - uses: "authzed/actions/go-test@main"

  development:
    name: "WASM Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/setup-go@main"
        with:
          cache: "false" # do not cache to prevent cache poisoning
      - name: "Install wasmbrowsertest"
        run: "go install github.com/agnivade/wasmbrowsertest@latest"
      - name: "Run WASM Tests"
        run: "GOOS=js GOARCH=wasm go test ./pkg/wasm/... -exec $(go env GOPATH)/bin/wasmbrowsertest"
